# Generated by Django 5.0 on 2026-02-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField(default='https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
