# Generated by Django 5.0 on 2026-02-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_userprofile_accomplishments_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
